In [1]:
from v2_utils import load_csv, run_pipeline

df_products = load_csv("data/products_dataset_raw.csv")
df_prices = load_csv("data/prices_raw.csv")

df_processed = run_pipeline(df_products, df_prices)
df_processed.head()

,product_name,brand,usage_type,category,ingredients,image_url,product_url,price
0,No7 Hydra Luminous Aqua Release Skin Perfector...,No7,Face,Tinted Moisturizers,"propylene glycol, alcohol denat, anhydroxylito...",https://cdn1.skinsafeproducts.com/photo/E84797...,https://www.skinsafeproducts.com/no7-hydra-lum...,15.29
1,"Tower 28 SOS Daily Rescue Facial Spray, 4 fl o...",Tower 28,Face,Spray Moisturizer,"hypochlorous acid, sodium chloride, water",https://cdn1.skinsafeproducts.com/photo/488026...,https://www.skinsafeproducts.com/tower-28-sos-...,5.48
2,"Clinique Takes the Day Off Cleansing Oil, 6.7 ...",Clinique,Facial Cleansers,Facial Cleansing Oil,"bht, caprylyl glycol, cetyl ethylhexanoate, gl...",https://cdn1.skinsafeproducts.com/photo/53EEB4...,https://www.skinsafeproducts.com/clinique-take...,43.95
3,"Necessaire The Body Lotion, Fragrance Free, 15...",Necessaire,Body,Lotions,"aqua/water/eau, caprylhydroxamic acid, capryli...",https://cdn1.skinsafeproducts.com/photo/D9ADD5...,https://www.skinsafeproducts.com/necessaire-th...,13.48
4,Paula’s Choice Resist Weightless Advanced Repa...,Paula'S Choice,Toners & Astringents,Toners,"acetyl glucosamine, adenosine, butylene glycol...",https://cdn1.skinsafeproducts.com/photo/2A9B12...,https://www.skinsafeproducts.com/paula-s-choic...,18.00

In [2]:
df_processed[['brand','product_name','price']].head()

            brand                                       product_name  price
0             No7  No7 Hydra Luminous Aqua Release Skin Perfector...  15.29
1        Tower 28  Tower 28 SOS Daily Rescue Facial Spray, 4 fl o...   5.48
2        Clinique  Clinique Takes the Day Off Cleansing Oil, 6.7 ...  43.95
3      Necessaire  Necessaire The Body Lotion, Fragrance Free, 15...  13.48
4  Paula'S Choice  Paula’s Choice Resist Weightless Advanced Repa...  18.00